# Generated by Django 4.1.7 on 2023-07-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='date_of_challenge_removal',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='illustrator',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='origin_of_challenge',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='ban',
            name='secondary_author',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='state',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='ban',
            name='translator',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='type_of_ban',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
