# Generated by Django 4.1.7 on 2023-07-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='date_of_challenge_removal',
            field=models.CharField(max_length=50),
        ),
    ]
